name: Notify Slack on Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: "🚀 A new push has been made to the main branch!"
          SLACK_USERNAME: "GitHub Actions"
          SLACK_ICON_EMOJI: ":octocat:"
