name: Slack Notification

on:
 workflow_dispatch:
 
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack message
        uses: slackapi/slack-github-action@v1
        with:
          channel-id: "#automation-reports"
          slack-message: "🚀 A new push to the main branch!"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
